import { TextEdit, LineEdit, GridBox, HorizontalBox, ScrollView, ProgressIndicator, Button, AboutSlint, StandardButton, ListView, SpinBox, Spinner, VerticalBox } from "std-widgets.slint";
import { AlertWindow } from "alertdialog.slint";

export component AppWindow inherits Window {
    in-out property <bool> app-state-enabled: false;

    out property <string> token: access-token.text;
    out property <string> container: container.text;
    out property <string> subdomain: sub-domain.text;
    in-out property <[string]> file-lists;
    in-out property <[string]> generated-urls: [];

    // Style
    title: "App Name";
    preferred-height: 800px;
    preferred-width: 1400px;
    height: 815px;
    width: 1400px;
    background: #272727;
    default-font-size: 14px;
    default-font-weight: 700;

    callback start-upload([string]);
    callback load-files();
    callback send-to-clipboard();

    property <string> message;
    property <bool> show-alert: false;

    popup := PopupWindow {
        max-height: 300px;
        height: 100px;
        width: 200px;
        x: 700px;
        y: 300px;
        close-on-click: false;

        Rectangle {
            background: #757575;
            border-radius: 15px;
            height: 100%;
            width: 100%;
            VerticalBox {
                Text {
                    wrap: word-wrap;
                    color: wheat;
                    text: "\{message}";
                }

                StandardButton {
                    kind: close;
                    clicked => {
                        message = "";
                        popup.close();
                    }
                }
            }
        }
    }

    /** Load file */
    Button {
        preferred-height: 32px;
        x: 905px;
        y: 373px;
        preferred-width: 123px;
        text: "Load Files";
        clicked => { root.load-files() }
    }

    /** Upload Button */
    Button {
        preferred-height: 32px;
        x: 906px;
        y: 327px;
        preferred-width: 123px;
        text: "Upload";
        clicked => {
            if (file-lists.length < 1) {
                message = "No file(s) detected!";
                popup.show();
            } else {
                start-upload(file-lists)
             }
        }
    }

    ProgressIndicator {
        height: 15px;
        width: 800px;
        progress: 1;
        x: 65px;
        y: 445px;
        preferred-width: 670px;
    }

    /** Clear file */
    Button {
        preferred-height: 32px;
        x: 906px;
        y: 420px;
        preferred-width: 123px;
        text: "Clear Files";
        clicked => { file-lists = []; }
    }

    /** Clear url */
    Button {
        preferred-height: 32px;
        x: 900px;
        y: 676px;
        preferred-width: 123px;
        text: "Clear URLs";
        clicked => { generated-urls = []; }
    }

    /** Copy urls */
    Button {
        preferred-height: 32px;
        x: 900px;
        y: 637px;
        preferred-width: 123px;
        text: "Copy";
        clicked => { send-to-clipboard() }
    }

    Text {
        preferred-height: 32px;
        preferred-width: 140px;
        color: #fff;
        font-size: 24px;
        font-weight: 800;
        horizontal-alignment: center;
        text: "List of File(s)";
        vertical-alignment: center;
        x: 33px;
        y: 29px;
    }

    sub-domain:= LineEdit {
        preferred-height: 42px;
        preferred-width: 440px;
        placeholder-text: "Sub-domain: (e.g artikel)";
        x: 907px;
        y: 140px;
        enabled: !app-state-enabled;
    }

    container:= LineEdit {
        enabled: !app-state-enabled;
        preferred-height: 42px;
        preferred-width: 440px;
        placeholder-text: "Container: (e.g $web)";
        x: 907px;
        y: 200px;
    }

    access-token:= LineEdit {
        enabled: !app-state-enabled;
        preferred-height: 42px;
        preferred-width: 440px;
        input-type: password;
        placeholder-text: "Access Token";
        x: 907px;
        y: 260px;
    }

    // List of loaded files
    Rectangle {
        preferred-width: 863px;
        preferred-height: 367px;
        width: 863px;
        height: root.height * 45%;
        border-radius: 30px;
        background: #1a1a1a;
        x: 32px;
        y: 72px;
        ListView {
            for file in file-lists: Rectangle {
                max-width: parent.width * 87%;
                border-width: 0.2px;
                border-color: #fff;
                border-radius: 5px;
                Text {
                    color: #fff;
                    max-width: parent.width;
                    wrap: word-wrap;
                    font-size: 14px;
                    text: file;
                }
            }
        }
    }

    // List of uploaded URLs
    Rectangle {
        width: 863px;
        height: root.height * 35%;
        x: 27px;
        y: 493px;
        background: #1a1a1a;
        border-radius: 30px;
        ListView {
            for url in generated-urls: Rectangle {
                border-width: 0.2px;
                border-color: #fff;
                border-radius: 5px;
                max-height: 30px;
                Text {
                    color: #fff;
                    width: 95%;
                    overflow: clip;
                    text: url;
                    wrap: word-wrap;
                 }
            }
        }
    }

    Text {
        preferred-width: 77px;
        preferred-height: 39px;
        vertical-alignment: center;
        color: white;
        text: "Status: ";
        x: 907px;
        y: 74px;
    }


    Text {
        preferred-width: 77px;
        preferred-height: 39px;
        vertical-alignment: center;
        font-size: 16px;
        font-weight: 700;
        x: 970px;
        y: 73px;
        z: 1;
        color: green;
        text: "READY";
    }

    AboutSlint {
        x: 1198px;
        y: 720px;
        width: 154px;
        height: 79px;
    }

    
    Image {
        height: 50px;
        source: @image-url("author.jpg");
        x: 1106px;
        y: 730px;
    }

    Button {
        x: 1006px;
        y: 736px;
        colorize-icon: false;
        icon: @image-url("telegram.png");
        preferred-width: 76px;
    }

}